In [2]:
from google.colab import files
files.upload()
files.upload()

Saving loan_train.csv to loan_train.csv
Saving loan_test.csv to loan_test.csv


{}

In [60]:
#data analysis libraries 
import numpy as np
import pandas as pd
train = pd.read_csv("loan_train.csv")
train.describe(include="all")

id     member_id  ...  total_bc_limit  total_il_high_credit_limit
count   2.499900e+04  2.499900e+04  ...             0.0                         0.0
unique           NaN           NaN  ...             NaN                         NaN
top              NaN           NaN  ...             NaN                         NaN
freq             NaN           NaN  ...             NaN                         NaN
mean    6.824732e+05  8.498388e+05  ...             NaN                         NaN
std     2.094886e+05  2.642564e+05  ...             NaN                         NaN
min     5.574200e+04  7.367300e+04  ...             NaN                         NaN
25%     5.165330e+05  6.672200e+05  ...             NaN                         NaN
50%     6.647370e+05  8.496710e+05  ...             NaN                         NaN
75%     8.355255e+05  1.044732e+06  ...             NaN                         NaN
max     1.076863e+06  1.304884e+06  ...             NaN                         NaN

[11 rows x 111 columns]

In [61]:
train.dropna(how='all', axis=1, inplace=True)
display(train)

id  member_id  ...  pub_rec_bankruptcies  tax_liens
0       573354     737474  ...                   0.0        0.0
1       476321     603324  ...                   0.0        0.0
2       451484     556265  ...                   0.0        0.0
3      1018129    1246557  ...                   2.0        0.0
4       800018    1005270  ...                   0.0        0.0
...        ...        ...  ...                   ...        ...
24994   450579     554340  ...                   0.0        0.0
24995   788033     991661  ...                   0.0        0.0
24996   568459     731299  ...                   0.0        0.0
24997   397594     428786  ...                   1.0        0.0
24998   660367     844601  ...                   0.0        0.0

[24999 rows x 57 columns]

In [62]:
print(pd.isnull(train).sum())


id                                0
member_id                         0
loan_amnt                         0
funded_amnt                       0
funded_amnt_inv                   0
term                              0
int_rate                          0
installment                       0
grade                             0
sub_grade                         0
emp_title                         6
emp_length                       41
home_ownership                    0
annual_inc                        0
verification_status               0
issue_d                           0
loan_status                       0
pymnt_plan                        0
url                               0
desc                           8192
purpose                           0
title                             8
zip_code                          0
addr_state                        0
dti                               0
delinq_2yrs                       0
earliest_cr_line                  0
inq_last_6mths              

In [63]:
train = train[train.loan_status != "Current"]

train.loc[train['loan_status'] =="Charged Off", 'loan_status'] = -1
train.loc[train['loan_status'] =="Fully Paid", 'loan_status'] = 1
display(train)

id  member_id  ...  pub_rec_bankruptcies  tax_liens
0      573354     737474  ...                   0.0        0.0
1      476321     603324  ...                   0.0        0.0
2      451484     556265  ...                   0.0        0.0
4      800018    1005270  ...                   0.0        0.0
5      471391     595223  ...                   0.0        0.0
...       ...        ...  ...                   ...        ...
24994  450579     554340  ...                   0.0        0.0
24995  788033     991661  ...                   0.0        0.0
24996  568459     731299  ...                   0.0        0.0
24997  397594     428786  ...                   1.0        0.0
24998  660367     844601  ...                   0.0        0.0

[24301 rows x 57 columns]

In [64]:
train=train.drop(['mths_since_last_record'], axis = 1)
train=train.drop(['next_pymnt_d'], axis = 1)

In [65]:
X=train.drop('loan_status',1)
y=train.loan_status
display(X)

id  member_id  ...  pub_rec_bankruptcies  tax_liens
0      573354     737474  ...                   0.0        0.0
1      476321     603324  ...                   0.0        0.0
2      451484     556265  ...                   0.0        0.0
4      800018    1005270  ...                   0.0        0.0
5      471391     595223  ...                   0.0        0.0
...       ...        ...  ...                   ...        ...
24994  450579     554340  ...                   0.0        0.0
24995  788033     991661  ...                   0.0        0.0
24996  568459     731299  ...                   0.0        0.0
24997  397594     428786  ...                   1.0        0.0
24998  660367     844601  ...                   0.0        0.0

[24301 rows x 54 columns]

In [66]:
for col_name in X.columns:
  if X[col_name].dtypes=='object':
    unique_cat=len(X[col_name].unique())
    print("Feature'{col_name}' has {unique_cat} unique categories".format(col_name=col_name,unique_cat=unique_cat))

Feature'term' has 2 unique categories
Feature'int_rate' has 361 unique categories
Feature'grade' has 7 unique categories
Feature'sub_grade' has 35 unique categories
Feature'emp_title' has 19414 unique categories
Feature'emp_length' has 12 unique categories
Feature'home_ownership' has 4 unique categories
Feature'verification_status' has 3 unique categories
Feature'issue_d' has 55 unique categories
Feature'pymnt_plan' has 1 unique categories
Feature'url' has 24301 unique categories
Feature'desc' has 16214 unique categories
Feature'purpose' has 14 unique categories
Feature'title' has 12699 unique categories
Feature'zip_code' has 783 unique categories
Feature'addr_state' has 50 unique categories
Feature'earliest_cr_line' has 495 unique categories
Feature'revol_util' has 1059 unique categories
Feature'initial_list_status' has 1 unique categories
Feature'last_pymnt_d' has 102 unique categories
Feature'last_credit_pull_d' has 102 unique categories
Feature'application_type' has 1 unique catego

In [67]:
for col_name in X.columns:
  
  unique_cat=len(X[col_name].unique())
  print("Feature'{col_name}' has {unique_cat} unique categories".format(col_name=col_name,unique_cat=unique_cat))

Feature'id' has 24301 unique categories
Feature'member_id' has 24301 unique categories
Feature'loan_amnt' has 762 unique categories
Feature'funded_amnt' has 929 unique categories
Feature'funded_amnt_inv' has 5415 unique categories
Feature'term' has 2 unique categories
Feature'int_rate' has 361 unique categories
Feature'installment' has 11351 unique categories
Feature'grade' has 7 unique categories
Feature'sub_grade' has 35 unique categories
Feature'emp_title' has 19414 unique categories
Feature'emp_length' has 12 unique categories
Feature'home_ownership' has 4 unique categories
Feature'annual_inc' has 3557 unique categories
Feature'verification_status' has 3 unique categories
Feature'issue_d' has 55 unique categories
Feature'pymnt_plan' has 1 unique categories
Feature'url' has 24301 unique categories
Feature'desc' has 16214 unique categories
Feature'purpose' has 14 unique categories
Feature'title' has 12699 unique categories
Feature'zip_code' has 783 unique categories
Feature'addr_stat

In [68]:
for col_name in X.columns:
  
  unique_cat=len(X[col_name].unique())
  if unique_cat==1:
    X=X.drop(col_name,1)

In [69]:
for col_name in X.columns:
  
  unique_cat=len(X[col_name].unique())
  print("Feature'{col_name}' has {unique_cat} unique categories".format(col_name=col_name,unique_cat=unique_cat))

Feature'id' has 24301 unique categories
Feature'member_id' has 24301 unique categories
Feature'loan_amnt' has 762 unique categories
Feature'funded_amnt' has 929 unique categories
Feature'funded_amnt_inv' has 5415 unique categories
Feature'term' has 2 unique categories
Feature'int_rate' has 361 unique categories
Feature'installment' has 11351 unique categories
Feature'grade' has 7 unique categories
Feature'sub_grade' has 35 unique categories
Feature'emp_title' has 19414 unique categories
Feature'emp_length' has 12 unique categories
Feature'home_ownership' has 4 unique categories
Feature'annual_inc' has 3557 unique categories
Feature'verification_status' has 3 unique categories
Feature'issue_d' has 55 unique categories
Feature'url' has 24301 unique categories
Feature'desc' has 16214 unique categories
Feature'purpose' has 14 unique categories
Feature'title' has 12699 unique categories
Feature'zip_code' has 783 unique categories
Feature'addr_state' has 50 unique categories
Feature'dti' has

In [70]:
X=X.drop(['id','member_id','url','desc','zip_code'],axis=1)

In [71]:
for col_name in X.columns:
  if X[col_name].dtypes=='object':
    unique_cat=len(X[col_name].unique())
    print("Feature'{col_name}' has {unique_cat} unique categories".format(col_name=col_name,unique_cat=unique_cat))

Feature'term' has 2 unique categories
Feature'int_rate' has 361 unique categories
Feature'grade' has 7 unique categories
Feature'sub_grade' has 35 unique categories
Feature'emp_title' has 19414 unique categories
Feature'emp_length' has 12 unique categories
Feature'home_ownership' has 4 unique categories
Feature'verification_status' has 3 unique categories
Feature'issue_d' has 55 unique categories
Feature'purpose' has 14 unique categories
Feature'title' has 12699 unique categories
Feature'addr_state' has 50 unique categories
Feature'earliest_cr_line' has 495 unique categories
Feature'revol_util' has 1059 unique categories
Feature'last_pymnt_d' has 102 unique categories
Feature'last_credit_pull_d' has 102 unique categories


In [72]:
print(X['emp_title'].value_counts().sort_values(ascending=False).head(50))

Bank of America                    107
IBM                                 65
AT&T                                57
Kaiser Permanente                   56
Lockheed Martin                     42
Department of Defense               35
JPMorgan Chase                      35
JP Morgan Chase                     35
Northrop Grumman                    34
Booz Allen Hamilton                 34
Best Buy                            30
Accenture                           30
Fidelity Investments                29
Comcast                             28
Home Depot                          27
General Electric                    23
Morgan Stanley                      23
Citigroup                           22
Columbia University                 21
Merrill Lynch                       21
American Express                    21
Department of Veterans Affairs      20
Department of Homeland Security     20
Internal Revenue Service            18
General Dynamics                    18
BAE Systems              

In [73]:
print(X['title'].value_counts().sort_values(ascending=False).head(50))

Debt Consolidation                1351
Debt Consolidation Loan           1022
Personal Loan                      429
Consolidation                      325
debt consolidation                 295
Home Improvement                   225
Debt consolidation                 219
Credit Card Consolidation          219
Personal                           188
Credit Card Loan                   185
Consolidation Loan                 176
Small Business Loan                160
personal loan                      151
Home Improvement Loan              149
personal                           138
Wedding Loan                       135
Loan                               131
consolidation                      115
Car Loan                           113
Credit Card Payoff                 103
Other Loan                          97
Credit Card Refinance               95
Wedding                             93
Consolidate                         80
Major Purchase Loan                 80
Credit Card              

In [74]:
print(X['last_pymnt_d'].value_counts().sort_values(ascending=False).head(80))

13-Mar    628
13-May    586
14-Dec    553
13-Feb    548
12-Aug    543
         ... 
9-Dec      61
10-Feb     46
10-Jan     42
9-Nov      41
9-Oct      34
Name: last_pymnt_d, Length: 80, dtype: int64


In [75]:
X['int_rate'] = X['int_rate'].str.rstrip('%').astype('float') / 100.0

In [76]:
X['revol_util'] = X['revol_util'].str.rstrip('%').astype('float') / 100.0

In [77]:
counts_ear=X['earliest_cr_line'].value_counts().sort_values(ascending=False)
X['earliest_cr_line']=[x if x=='nan' or counts_ear[x]>=35 else 'Other' for x in X['earliest_cr_line']]
c_ear=X['earliest_cr_line']
print(X['earliest_cr_line'].value_counts().sort_values(ascending=False).head(200))


Other     2526
Nov-98     239
Oct-99     230
Dec-98     227
Oct-00     207
          ... 
7-Jan       47
7-Mar       47
Sep-90      46
Jul-88      46
Nov-92      46
Name: earliest_cr_line, Length: 200, dtype: int64


In [78]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(X))
X=pd.DataFrame(data=imp.fit_transform(X),columns=X.columns)
display(X)
print(pd.isnull(X).sum())



[[10000 10000 9950.0 ... 0.0 0.0 0.0]
 [15000 15000 14800.0 ... 0.0 0.0 0.0]
 [2000 2000 2000.0 ... 0.0 0.0 0.0]
 ...
 [24000 24000 21100.31424 ... 0.0 0.0 0.0]
 [14000 14000 11411.12089 ... 0.0 1.0 0.0]
 [13400 13400 13400.0 ... 0.0 0.0 0.0]]


loan_amnt funded_amnt  ... pub_rec_bankruptcies tax_liens
0         10000       10000  ...                    0         0
1         15000       15000  ...                    0         0
2          2000        2000  ...                    0         0
3         14000       14000  ...                    0         0
4         12000       12000  ...                    0         0
...         ...         ...  ...                  ...       ...
24296      5500        5500  ...                    0         0
24297     11450       11450  ...                    0         0
24298     24000       24000  ...                    0         0
24299     14000       14000  ...                    1         0
24300     13400       13400  ...                    0         0

[24301 rows x 41 columns]

loan_amnt                     0
funded_amnt                   0
funded_amnt_inv               0
term                          0
int_rate                      0
installment                   0
grade                         0
sub_grade                     0
emp_title                     0
emp_length                    0
home_ownership                0
annual_inc                    0
verification_status           0
issue_d                       0
purpose                       0
title                         0
addr_state                    0
dti                           0
delinq_2yrs                   0
earliest_cr_line              0
inq_last_6mths                0
mths_since_last_delinq        0
open_acc                      0
pub_rec                       0
revol_bal                     0
revol_util                    0
total_acc                     0
total_pymnt                   0
total_pymnt_inv               0
total_rec_prncp               0
total_rec_int                 0
total_re

In [79]:

X=X.drop(['mths_since_last_delinq'],1)

In [80]:
counts_emp_title=X['emp_title'].value_counts().sort_values(ascending=False)
X['emp_title']=[x if  counts_emp_title[x]>=5 else 'Other1' for x in X['emp_title']]
c_emp=X['emp_title']
print(X['emp_title'].value_counts().sort_values(ascending=False))

Other1                            21624
Bank of America                     113
IBM                                  65
AT&T                                 57
Kaiser Permanente                    56
                                  ...  
Emory University                      5
Infor Global Solutions                5
Dept of Veterans Affairs              5
Paychex Inc                           5
New York Presbyterian Hospital        5
Name: emp_title, Length: 260, dtype: int64


In [81]:
counts_title=X['title'].value_counts().sort_values(ascending=False)
X['title']=[x if  counts_title[x]>=50 else 'Other2' for x in X['title']]
c_t=X['title']
print(X['title'].value_counts().sort_values(ascending=False))

Other2                       17573
Debt Consolidation            1359
Debt Consolidation Loan       1022
Personal Loan                  429
Consolidation                  325
debt consolidation             295
Home Improvement               225
Debt consolidation             219
Credit Card Consolidation      219
Personal                       188
Credit Card Loan               185
Consolidation Loan             176
Small Business Loan            160
personal loan                  151
Home Improvement Loan          149
personal                       138
Wedding Loan                   135
Loan                           131
consolidation                  115
Car Loan                       113
Credit Card Payoff             103
Other Loan                      97
Credit Card Refinance           95
Wedding                         93
Major Purchase Loan             80
Consolidate                     80
Credit Card                     73
home improvement                72
Medical             

In [82]:
counts_payd=X['last_pymnt_d'].value_counts().sort_values(ascending=False)
X['last_pymnt_d']=[x if  counts_payd[x]>=90 else 'Other3' for x in X['last_pymnt_d']]
c_last=X['last_pymnt_d']
print(X['last_pymnt_d'].value_counts().sort_values(ascending=False))

Other3    804
13-Mar    673
13-May    586
14-Dec    553
13-Feb    548
         ... 
16-Feb    103
10-Jul    102
10-Aug    102
10-Mar     97
15-Apr     93
Name: last_pymnt_d, Length: 72, dtype: int64


In [83]:
c_home=X['home_ownership'].value_counts().sort_values(ascending=False)

In [84]:
counts_pulld=X['last_credit_pull_d'].value_counts().sort_values(ascending=False)
X['last_credit_pull_d']=[x if  counts_pulld[x]>=100 else 'Other4' for x in X['last_credit_pull_d']]
c_credit=X['last_credit_pull_d']
print(X['last_credit_pull_d'].value_counts().sort_values(ascending=False))

16-May    5932
16-Apr    1526
Other4    1168
16-Mar     723
13-Feb     504
16-Feb     453
15-Dec     418
16-Jan     412
15-Sep     361
13-Mar     352
14-Mar     351
15-Jul     349
15-Nov     346
14-Dec     339
14-Aug     338
14-Oct     334
14-Jan     332
15-Oct     331
14-Jul     329
14-Feb     328
14-Sep     321
14-Apr     318
14-May     300
14-Nov     299
13-Nov     298
15-Aug     284
13-May     281
14-Jun     273
15-May     272
15-Jan     266
13-Apr     266
13-Dec     260
12-Nov     258
13-Oct     253
13-Jul     248
12-Aug     247
13-Jun     247
15-Feb     245
15-Mar     242
15-Apr     241
13-Sep     240
15-Jun     238
12-Sep     238
12-Feb     237
13-Aug     235
12-Dec     217
12-Oct     206
12-May     200
12-Mar     199
12-Apr     187
12-Jul     182
12-Jun     179
12-Jan     164
11-Mar     158
11-Aug     155
11-Dec     155
11-Nov     134
11-May     119
11-Sep     113
11-Jul     100
Name: last_credit_pull_d, dtype: int64


In [85]:

todummy_list=['term','grade','sub_grade','emp_title','emp_length','home_ownership','verification_status','issue_d','purpose','title','addr_state','earliest_cr_line','last_pymnt_d','last_credit_pull_d']
def dummy_df(df,todummmy_list):
  for x in todummmy_list:
    dummies=pd.get_dummies(df[x],prefix=x, dummy_na=False)
    df=df.drop(x,1)
    df=pd.concat([df,dummies],axis=1)
  return df


In [86]:
X=dummy_df(X,todummy_list)
display(X)
X_org=X

loan_amnt  ... last_credit_pull_d_Other4
0         10000  ...                         0
1         15000  ...                         1
2          2000  ...                         0
3         14000  ...                         0
4         12000  ...                         1
...         ...  ...                       ...
24296      5500  ...                         0
24297     11450  ...                         0
24298     24000  ...                         0
24299     14000  ...                         0
24300     13400  ...                         0

[24301 rows x 864 columns]

In [87]:
display(X)

loan_amnt  ... last_credit_pull_d_Other4
0         10000  ...                         0
1         15000  ...                         1
2          2000  ...                         0
3         14000  ...                         0
4         12000  ...                         1
...         ...  ...                       ...
24296      5500  ...                         0
24297     11450  ...                         0
24298     24000  ...                         0
24299     14000  ...                         0
24300     13400  ...                         0

[24301 rows x 864 columns]

In [88]:
import pandas as pd
from sklearn import preprocessing
X__=X
x = X.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
X = pd.DataFrame(x_scaled)
display(X)

0         1         2         3    ...  860  861  862  863
0      0.275362  0.275362  0.284286  0.110116  ...  0.0  0.0  0.0  0.0
1      0.420290  0.420290  0.422857  0.185458  ...  0.0  0.0  0.0  1.0
2      0.043478  0.043478  0.057143  0.429399  ...  0.0  0.0  0.0  0.0
3      0.391304  0.391304  0.400000  0.635933  ...  0.0  0.0  1.0  0.0
4      0.333333  0.333333  0.340000  0.185458  ...  0.0  0.0  0.0  1.0
...         ...       ...       ...       ...  ...  ...  ...  ...  ...
24296  0.144928  0.144928  0.157143  0.502634  ...  0.0  0.0  0.0  0.0
24297  0.317391  0.317391  0.327143  0.161749  ...  0.0  0.0  1.0  0.0
24298  0.681159  0.681159  0.602866  0.796101  ...  0.0  0.0  1.0  0.0
24299  0.391304  0.391304  0.326032  0.640674  ...  0.0  0.0  0.0  0.0
24300  0.373913  0.373913  0.382857  0.402529  ...  0.0  0.0  0.0  0.0

[24301 rows x 864 columns]

In [89]:
test = pd.read_csv("loan_test.csv")
test.dropna(how='all', axis=1, inplace=True)
test = test[test.loan_status != "Current"]

test.loc[test['loan_status'] =="Charged Off", 'loan_status'] = -1
test.loc[test['loan_status'] =="Fully Paid", 'loan_status'] = 1
test=test.drop(['mths_since_last_record','mths_since_last_delinq','next_pymnt_d','id','member_id','url','desc','zip_code'], axis = 1)
X_test=test.drop('loan_status',1)
y_test=test.loan_status

for col_name in X_test.columns:
  
  unique_cat=len(X_test[col_name].unique())
  if unique_cat==1:
    X_test=X_test.drop(col_name,1)

X_test['int_rate'] = X_test['int_rate'].str.rstrip('%').astype('float') / 100.0
X_test['revol_util'] = X_test['revol_util'].str.rstrip('%').astype('float') / 100.0
display(X_test)
X_test['earliest_cr_line']=[x if x in c_ear else 'Other' for x in X_test['earliest_cr_line']]
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="most_frequent")
print(imp.fit_transform(X_test))
X_test=pd.DataFrame(data=imp.fit_transform(X_test),columns=X_test.columns)
X_test['emp_title']=[x if x in c_emp else 'Other1' for x in X_test['emp_title']]
X_test['title']=[x if x in c_t else 'Other2' for x in X_test['title']]
X_test['last_pymnt_d']=[x if x in c_last else 'Other3' for x in X_test['last_pymnt_d']]
X_test['last_credit_pull_d']=[x if x in c_credit else 'Other4' for x in X_test['last_credit_pull_d']]
X_test['home_ownership']=[x if x in c_home else 'RENT' for x in X_test['home_ownership']]
X_test=dummy_df(X_test,todummy_list)
display(X_test)


loan_amnt  funded_amnt  ...  pub_rec_bankruptcies tax_liens
0           4200         4200  ...                   0.0       0.0
1           1325         1325  ...                   0.0       0.0
2          10000        10000  ...                   0.0       0.0
3           6000         6000  ...                   0.0       0.0
4          25000        25000  ...                   0.0       0.0
...          ...          ...  ...                   ...       ...
14713       5400         5400  ...                   NaN       NaN
14714       3000         3000  ...                   NaN       NaN
14715       5000         5000  ...                   NaN       NaN
14716       5000         5000  ...                   NaN       NaN
14717       5000         5000  ...                   NaN       NaN

[14276 rows x 40 columns]

[[4200 4200 4200.0 ... 0.0 0.0 0.0]
 [1325 1325 1325.0 ... 0.0 0.0 0.0]
 [10000 10000 9975.0 ... 0.0 0.0 0.0]
 ...
 [5000 5000 150.0 ... 0.0 0.0 0.0]
 [5000 5000 1325.0 ... 0.0 0.0 0.0]
 [5000 5000 650.0 ... 0.0 0.0 0.0]]


loan_amnt funded_amnt  ... last_pymnt_d_Other3 last_credit_pull_d_Other4
0          4200        4200  ...                   1                         1
1          1325        1325  ...                   1                         1
2         10000       10000  ...                   1                         1
3          6000        6000  ...                   1                         1
4         25000       25000  ...                   1                         1
...         ...         ...  ...                 ...                       ...
14271      5400        5400  ...                   1                         1
14272      3000        3000  ...                   1                         1
14273      5000        5000  ...                   1                         1
14274      5000        5000  ...                   1                         1
14275      5000        5000  ...                   1                         1

[14276 rows x 210 columns]

In [90]:
tmp=np.zeros(14276)
for col in X_org.columns:
  if col in X_test.columns:
    continue
  else:
    ind = X_org.columns.get_loc(col)
    X_test.insert(ind, col, tmp) 
  


In [92]:
X_test_=X_test
x_t = X_test.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_t_scaled = min_max_scaler.fit_transform(x_t)
X_test = pd.DataFrame(x_t_scaled)
display(X_test)

0         1         2         3    ...  860  861  862  863
0      0.107246  0.107246  0.120000  0.064900  ...  0.0  0.0  0.0  0.0
1      0.023913  0.023913  0.037857  0.436452  ...  0.0  0.0  0.0  0.0
2      0.275362  0.275362  0.285000  0.190373  ...  0.0  0.0  0.0  0.0
3      0.159420  0.159420  0.171429  0.598702  ...  0.0  0.0  0.0  0.0
4      0.710145  0.710145  0.714286  0.529475  ...  0.0  0.0  0.0  0.0
...         ...       ...       ...       ...  ...  ...  ...  ...  ...
14271  0.142029  0.142029  0.005714  0.126014  ...  0.0  0.0  0.0  0.0
14272  0.072464  0.072464  0.027143  0.177393  ...  0.0  0.0  0.0  0.0
14273  0.130435  0.130435  0.004286  0.143321  ...  0.0  0.0  0.0  0.0
14274  0.130435  0.130435  0.037857  0.143321  ...  0.0  0.0  0.0  0.0
14275  0.130435  0.130435  0.018571  0.108707  ...  0.0  0.0  0.0  0.0

[14276 rows x 864 columns]

In [93]:
y_test.value_counts().sort_values(ascending=False)

 1    12123
-1     2153
Name: loan_status, dtype: int64

In [109]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
# fit the model on the whole dataset
y=y.astype('int')
model.fit(X, y)
y_test=y_test.astype('int')
print(model.score(X_test, y_test))
predictions = model.predict(X_test)
confusion_matrix(y_test,predictions)
print(classification_report(y_test, predictions))

0.991874474642757
              precision    recall  f1-score   support

          -1       1.00      0.95      0.97      2153
           1       0.99      1.00      1.00     12123

    accuracy                           0.99     14276
   macro avg       1.00      0.97      0.98     14276
weighted avg       0.99      0.99      0.99     14276



In [110]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=10)
# fit the model on the whole dataset
y=y.astype('int')
model.fit(X, y)
y_test=y_test.astype('int')
print(model.score(X_test, y_test))
predictions = model.predict(X_test)
confusion_matrix(y_test,predictions)
print(classification_report(y_test, predictions))

0.97219108994116
              precision    recall  f1-score   support

          -1       1.00      0.82      0.90      2153
           1       0.97      1.00      0.98     12123

    accuracy                           0.97     14276
   macro avg       0.98      0.91      0.94     14276
weighted avg       0.97      0.97      0.97     14276



In [111]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(learning_rate=0.1,n_estimators=300)
# fit the model on the whole dataset
y=y.astype('int')
model.fit(X, y)
y_test=y_test.astype('int')
print(model.score(X_test, y_test))
predictions = model.predict(X_test)
confusion_matrix(y_test,predictions)
print(classification_report(y_test, predictions))

0.9942560941440179
              precision    recall  f1-score   support

          -1       1.00      0.96      0.98      2153
           1       0.99      1.00      1.00     12123

    accuracy                           0.99     14276
   macro avg       1.00      0.98      0.99     14276
weighted avg       0.99      0.99      0.99     14276



In [112]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(learning_rate=1,n_estimators=300)
# fit the model on the whole dataset
y=y.astype('int')
model.fit(X, y)
y_test=y_test.astype('int')
print(model.score(X_test, y_test))
predictions = model.predict(X_test)
confusion_matrix(y_test,predictions)
print(classification_report(y_test, predictions))

0.9939058559820678
              precision    recall  f1-score   support

          -1       1.00      0.96      0.98      2153
           1       0.99      1.00      1.00     12123

    accuracy                           0.99     14276
   macro avg       1.00      0.98      0.99     14276
weighted avg       0.99      0.99      0.99     14276



In [113]:
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(learning_rate=1,n_estimators=1000)
# fit the model on the whole dataset
y=y.astype('int')
model.fit(X, y)
y_test=y_test.astype('int')
print(model.score(X_test, y_test))
predictions = model.predict(X_test)
confusion_matrix(y_test,predictions)
print(classification_report(y_test, predictions))

0.9952367609974783
              precision    recall  f1-score   support

          -1       1.00      0.97      0.98      2153
           1       0.99      1.00      1.00     12123

    accuracy                           1.00     14276
   macro avg       1.00      0.98      0.99     14276
weighted avg       1.00      1.00      1.00     14276



In [114]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy',random_state=0)
clf.fit(X, y)
predictions = clf.predict(X_test)
print(classification_report(y_test, predictions))
print(clf.score(X_test, y_test))

              precision    recall  f1-score   support

          -1       1.00      0.92      0.96      2153
           1       0.99      1.00      0.99     12123

    accuracy                           0.99     14276
   macro avg       0.99      0.96      0.98     14276
weighted avg       0.99      0.99      0.99     14276

0.9876716166993555
